# Generated by Django 4.1.1 on 2022-09-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeCareApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fechaNacimiento',
            field=models.DateField(),
        ),
    ]
